config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources :posts
  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :reviews
    validates :title, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy]
  def index
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(3)
    @new_posts = Post.order(created_at: :desc).limit(5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to "/posts/#{@post.id}"
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def destroy
    @post.destroy
    redirect_to "/posts"
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body, :category)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to controller: 'posts', action: 'show', id: @review.post.id, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:post_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Takuma's elite Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
</head>
<body>
  
  <!-- ここから追加 -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
      <a class="navbar-brand" href="/posts/">My blog</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
        <li><%= link_to "投稿する", new_post_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

<!-- ここまで追加 -->

</body>
</html>

app/views/posts/_new_review.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :post_id %>
  
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>ブログ記事編集</h1>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "本文" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit '更新する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="col-md-12">
 <div class="form-inline pull-right" style="margin-bottom:10px;">
   <%= search_form_for @q do |f| %>
     <div class="form-group">
       <%= f.search_field :title_or_body_cont, placeholder: "タイトルか本文を検索", class: "form-control" %>
       <%= f.submit "検索", class: "btn btn-primary" %>
     </div>
   <% end %>
 </div>
</div>
<div class="row">

    <div class="col-md-8">
      <% @posts.each do |post| %>
        <div class="article">
          <h2>タイトル：<%= post.title %></h2>
          <p>カテゴリ：<%= post.category %></p>
          <p>作成日：<%= post.created_at %></p>
          <p><%= truncate(post.body, length: 50) %></p>
          <p><%= link_to "続きを読む", post, class: "btn btn-default" %></p>
        </div>
      <% end %>
      
      <%= paginate @posts %>
      
    </div>
    
    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag Author.first.image_url, alt: "著者イメージ" %>
        <div class="caption">
          <h3>著者名：<%= Author.first.name %></h3>
          <p>詳細：<%= Author.first.description %></p>
        </div>
      </div>
      <div class="list-group">
        <% @new_posts.each do |post| %>
        <%= link_to post.title, post, class: "list-group-item" %>
        <% end %>
      </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
  <h1>ブログ記事投稿</h1>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "本文" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p>カテゴリ: <%= @post.category %></p>
  <p>投稿日:<%= @post.created_at %></p>
  <hr>
  <p>
    <%= simple_format(@post.body) %>
  </p>
  
  <h3>レビュー一覧</h3>
    <% @post.reviews.each do |review| %>
  <li><%= review.body %> - <%= review.created_at %></li>
    <% end %>
    
    <h3>投稿</h3>
    <%= render partial: 'new_review', locals: { review: Review.new(post_id: @post.id) } %>
  
  <hr>
  <%= link_to "編集", edit_post_path(@post), class: "btn btn-default" %>
  <%= link_to "削除", post_path(@post), class: "btn btn-default", method: :delete %>
</div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.post_id %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @review.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>